# ~/.config/xico/config.toml

# [awesome.layout]
# base = '~/.config/awesome/themes/meta/icons/layout'
# icons = [
#   ['â››', 'dummy_floating.png'],
#   ['ğº', 'dummy_tile.png'],
#   ['î˜«', 'dummy_tile.png'],
# ]

# [awesome.tags]
# icons = [
#   ['â–£', '~/.config/awesome/themes/meta/tags/demo_tag.png'],
#   ['â–£', '~/.config/awesome/icon/demo.png'],
# ]

# [somekey]
# icons = [
#   ['âŠ–', '/tmp/demo_1.png'],
#   ['â—ª', '/tmp/ohhh_2.png'],
# ]
